{ The jigs example.  Unlike the others, jigs.hsk is made in the program itself
  (it shows what jigs printed), so this only carries it into
  ../src/examples/hsExJigs.pas.  Run it from this folder after saving a new jigs.hsk:
      fpc -Mobjfpc -Sh -Fu"../src/*" -Fu"../src/vendor/*" -Fi.. make-jigs.pas && ./make-jigs   }
program makejigsexample;
{$mode objfpc}{$H+}
uses Classes, SysUtils, exwrite;
var
  U, L: TStringList;
begin
  L := TStringList.Create;
  U := TStringList.Create;
  L.LoadFromFile('jigs.hsk');
  U.Add('unit hsExJigs;');
  U.Add('');
  U.Add('{ The jigs example.');
  U.Add('');
  U.Add('  Generated by examples/make-jigs.pas from examples/jigs.hsk - do not edit');
  U.Add('  this by hand.  It is the same drawing, carried inside the program so');
  U.Add('  that a portable build is one file. }');
  U.Add('');
  U.Add('{$mode objfpc}{$H+}');
  U.Add('');
  U.Add('interface');
  U.Add('');
  U.Add('uses');
  U.Add('  Classes;');
  U.Add('');
  U.Add('{ Four groups, each made by a jig, as the lines of a .hsk file. }');
  U.Add('procedure JigsDrawing(L: TStrings);');
  U.Add('');
  U.Add('implementation');
  Lines2Unit(L, U, 'procedure JigsDrawing(L: TStrings);');
  U.SaveToFile('../src/examples/hsExJigs.pas');
  WriteLn('wrote ../src/examples/hsExJigs.pas: ', L.Count, ' lines');
end.
