unit hsExJigs;

{ The jigs example.

  Generated by examples/make-jigs.pas from examples/jigs.hsk - do not edit
  this by hand.  It is the same drawing, carried inside the program so
  that a portable build is one file. }

{$mode objfpc}{$H+}

interface

uses
  Classes;

{ Four groups, each made by a jig, as the lines of a .hsk file. }
procedure JigsDrawing(L: TStrings);

implementation

procedure JigsDrawing(L: TStrings);
begin
  L.Add('HeckersSketch 2');
  L.Add('units = ft in');
  L.Add('');
  L.Add('sheet ''Jigs''');
  L.Add('  ink = #1A1C20');
  L.Add('  width = 1');
  L.Add('  units = ft in');
  L.Add('  scale = ''1/4"''');
  L.Add('  snap = ''1/16"''');
  L.Add('  view = 3d');
  L.Add('  camera = -0.95, 0.5, 1.25, 330, 470');
  L.Add('');
  L.Add('  circle c1');
  L.Add('    center = 2'' east, 2'' north, 4'' up');
  L.Add('    radius = 1''');
  L.Add('    facing = up');
  L.Add('    sides = 48');
  L.Add('  end');
  L.Add('  line = 0 east, 0 north, 0 up to 4'' east, 0 north, 0 up');
  L.Add('  line = 4'' east, 0 north, 0 up to 4'' east, 4'' north, 0 up');
  L.Add('  line = 4'' east, 4'' north, 0 up to 0 east, 4'' north, 0 up');
  L.Add('  line = 0 east, 4'' north, 0 up to 0 east, 0 north, 0 up');
  L.Add('  line = 0 east, 0 north, 4'' up to 4'' east, 0 north, 4'' up');
  L.Add('  line = 4'' east, 0 north, 4'' up to 4'' east, 4'' north, 4'' up');
  L.Add('  line = 4'' east, 4'' north, 4'' up to 0 east, 4'' north, 4'' up');
  L.Add('  line = 0 east, 4'' north, 4'' up to 0 east, 0 north, 4'' up');
  L.Add('  line = 0 east, 0 north, 0 up to 0 east, 0 north, 4'' up');
  L.Add('  line = 4'' east, 0 north, 0 up to 4'' east, 0 north, 4'' up');
  L.Add('  line = 4'' east, 4'' north, 0 up to 4'' east, 4'' north, 4'' up');
  L.Add('  line = 0 east, 4'' north, 0 up to 0 east, 4'' north, 4'' up');
  L.Add('  line = 6'' east, 0 north, 0 up to 6'' east, 3'' north, 0 up');
  L.Add('  line = 6'' east, 3'' north, 0 up to 8'' east, 3'' north, 1'' 6" up');
  L.Add('  line');
  L.Add('    points = 6'' east, 0 north, 0 up to 8'' east, 3'' north, 1'' 6" up');
  L.Add('    ink = red');
  L.Add('    width = 2');
  L.Add('  end');
  L.Add('  noface = (');
  L.Add('    0 east, 11'' north, 10.8" up to + 1'' 6" up to + 2'' east to + 1'' 6" down');
  L.Add('  )');
  L.Add('  noface = (');
  L.Add('    2'' east, 11'' north, 10.8" up to + 1'' 6" up to + 2'' east to + 1'' 6" down');
  L.Add('  )');
  L.Add('  noface = (');
  L.Add('    4'' east, 11'' north, 10.8" up to + 1'' 6" up to + 2'' east to + 1'' 6" down');
  L.Add('  )');
  L.Add('  noface = (');
  L.Add('    6'' east, 11'' north, 10.8" up to + 1'' 6" up to + 2'' east to + 1'' 6" down');
  L.Add('  )');
  L.Add('  noface = (');
  L.Add('    8'' east, 11'' north, 10.8" up to + 1'' 6" up to + 2'' east to + 1'' 6" down');
  L.Add('  )');
  L.Add('  group ''Star''');
  L.Add('    jig = ''star'' with Points = 5, Radius = 2'', East = 12'', North = 2''');
  L.Add('    line = 12'' east, 4'' north, 0 up to 138.3573" east, 31.766604" north, 0 up');
  L.Add('    line = 138.3573" east, 31.766604" north, 0 up to 121.174596" east, 31.416396" north, 0 up');
  L.Add('    line = 121.174596" east, 31.416396" north, 0 up to 134.869896" east, 21.033396" north, 0 up');
  L.Add('    line = 134.869896" east, 21.033396" north, 0 up to 129.893196" east, 4.583604" north, 0 up');
  L.Add('    line = 129.893196" east, 4.583604" north, 0 up to 12'' east, 14.4" north, 0 up');
  L.Add('    line = 12'' east, 14.4" north, 0 up to 158.106804" east, 4.583604" north, 0 up');
  L.Add('    line = 158.106804" east, 4.583604" north, 0 up to 153.130104" east, 21.033396" north, 0 up');
  L.Add('    line = 153.130104" east, 21.033396" north, 0 up to 166.825404" east, 31.416396" north, 0 up');
  L.Add('    line = 166.825404" east, 31.416396" north, 0 up to 149.6427" east, 31.766604" north, 0 up');
  L.Add('    line = 149.6427" east, 31.766604" north, 0 up to 12'' east, 4'' north, 0 up');
  L.Add('  end');
  L.Add('  group ''Balloon''');
  L.Add('    jig = ''balloon'' with Radius = 1'' 6", East = 12'', North = 7'', Height = 6''');
  L.Add('    circle c2');
  L.Add('      center = 12'' east, 7'' north, 6'' up');
  L.Add('      radius = 1'' 6"');
  L.Add('      facing = south');
  L.Add('      sides = 48');
  L.Add('      ink = red');
  L.Add('    end');
  L.Add('    line = 12'' east, 7'' north, 4'' 6" up to 11'' 9 3/4" east, 7'' north, 4'' 3 3/4" up');
  L.Add('    line = 11'' 9 3/4" east, 7'' north, 4'' 3 3/4" up to 12'' 2 1/4" east, 7'' north, 4'' 3 3/4" up');
  L.Add('    line = 12'' 2 1/4" east, 7'' north, 4'' 3 3/4" up to 12'' east, 7'' north, 4'' 6" up');
  L.Add('    line = 12'' east, 7'' north, 4'' 3 3/4" up to 146.598096" east, 7'' north, 3'' 11 7/16" up');
  L.Add('    line = 146.598096" east, 7'' north, 3'' 11 7/16" up to 146.598096" east, 7'' north, 3'' 7 1/8" up');
  L.Add('    line = 146.598096" east, 7'' north, 3'' 7 1/8" up to 12'' east, 7'' north, 3'' 2 13/16" up');
  L.Add('    line = 12'' east, 7'' north, 3'' 2 13/16" up to 141.401904" east, 7'' north, 2'' 10 1/2" up');
  L.Add('    line = 141.401904" east, 7'' north, 2'' 10 1/2" up to 141.401904" east, 7'' north, 2'' 6 3/16" up');
  L.Add('    line = 141.401904" east, 7'' north, 2'' 6 3/16" up to 12'' east, 7'' north, 2'' 1 7/8" up');
  L.Add('    line = 12'' east, 7'' north, 2'' 1 7/8" up to 146.598096" east, 7'' north, 1'' 9 9/16" up');
  L.Add('    line = 146.598096" east, 7'' north, 1'' 9 9/16" up to 146.598096" east, 7'' north, 1'' 5 1/4" up');
  L.Add('    line = 146.598096" east, 7'' north, 1'' 5 1/4" up to 12'' east, 7'' north, 1'' 15/16" up');
  L.Add('    line = 12'' east, 7'' north, 1'' 15/16" up to 141.401904" east, 7'' north, 8 5/8" up');
  L.Add('    line = 141.401904" east, 7'' north, 8 5/8" up to 141.401904" east, 7'' north, 4 5/16" up');
  L.Add('    line = 141.401904" east, 7'' north, 4 5/16" up to 12'' east, 7'' north, 0 up');
  L.Add('  end');
  L.Add('  group ''Fence''');
  L.Add('    jig = ''fence'' with Posts = 6, Spacing = 2'', Height = 3'', North = 11''');
  L.Add('    line = 0 east, 11'' north, 0 up to 0 east, 11'' north, 3'' up');
  L.Add('    line = 2'' east, 11'' north, 0 up to 2'' east, 11'' north, 3'' up');
  L.Add('    line = 4'' east, 11'' north, 0 up to 4'' east, 11'' north, 3'' up');
  L.Add('    line = 6'' east, 11'' north, 0 up to 6'' east, 11'' north, 3'' up');
  L.Add('    line = 8'' east, 11'' north, 0 up to 8'' east, 11'' north, 3'' up');
  L.Add('    line = 10'' east, 11'' north, 0 up to 10'' east, 11'' north, 3'' up');
  L.Add('    line = 0 east, 11'' north, 10.8" up to 10'' east, 11'' north, 10.8" up');
  L.Add('    line = 0 east, 11'' north, 28.8" up to 10'' east, 11'' north, 28.8" up');
  L.Add('  end');
  L.Add('  group ''Steps''');
  L.Add('    jig = ''steps'' with Steps = 5, Rise = 7 1/2", Run = 10", Width = 3'', East = 6'', North = 5''');
  L.Add('    line = 6'' east, 5'' north, 0 up to 6'' east, 5'' north, 7 1/2" up');
  L.Add('    line = 6'' east, 5'' north, 7 1/2" up to 6'' 10" east, 5'' north, 7 1/2" up');
  L.Add('    line = 6'' 10" east, 5'' north, 7 1/2" up to 6'' 10" east, 5'' north, 1'' 3" up');
  L.Add('    line = 6'' 10" east, 5'' north, 1'' 3" up to 7'' 8" east, 5'' north, 1'' 3" up');
  L.Add('    line = 7'' 8" east, 5'' north, 1'' 3" up to 7'' 8" east, 5'' north, 1'' 10 1/2" up');
  L.Add('    line = 7'' 8" east, 5'' north, 1'' 10 1/2" up to 8'' 6" east, 5'' north, 1'' 10 1/2" up');
  L.Add('    line = 8'' 6" east, 5'' north, 1'' 10 1/2" up to 8'' 6" east, 5'' north, 2'' 6" up');
  L.Add('    line = 8'' 6" east, 5'' north, 2'' 6" up to 9'' 4" east, 5'' north, 2'' 6" up');
  L.Add('    line = 9'' 4" east, 5'' north, 2'' 6" up to 9'' 4" east, 5'' north, 3'' 1 1/2" up');
  L.Add('    line = 9'' 4" east, 5'' north, 3'' 1 1/2" up to 10'' 2" east, 5'' north, 3'' 1 1/2" up');
  L.Add('    line = 6'' east, 8'' north, 0 up to 6'' east, 8'' north, 7 1/2" up');
  L.Add('    line = 6'' east, 8'' north, 7 1/2" up to 6'' 10" east, 8'' north, 7 1/2" up');
  L.Add('    line = 6'' 10" east, 8'' north, 7 1/2" up to 6'' 10" east, 8'' north, 1'' 3" up');
  L.Add('    line = 6'' 10" east, 8'' north, 1'' 3" up to 7'' 8" east, 8'' north, 1'' 3" up');
  L.Add('    line = 7'' 8" east, 8'' north, 1'' 3" up to 7'' 8" east, 8'' north, 1'' 10 1/2" up');
  L.Add('    line = 7'' 8" east, 8'' north, 1'' 10 1/2" up to 8'' 6" east, 8'' north, 1'' 10 1/2" up');
  L.Add('    line = 8'' 6" east, 8'' north, 1'' 10 1/2" up to 8'' 6" east, 8'' north, 2'' 6" up');
  L.Add('    line = 8'' 6" east, 8'' north, 2'' 6" up to 9'' 4" east, 8'' north, 2'' 6" up');
  L.Add('    line = 9'' 4" east, 8'' north, 2'' 6" up to 9'' 4" east, 8'' north, 3'' 1 1/2" up');
  L.Add('    line = 9'' 4" east, 8'' north, 3'' 1 1/2" up to 10'' 2" east, 8'' north, 3'' 1 1/2" up');
  L.Add('    line = 6'' east, 5'' north, 0 up to 6'' east, 8'' north, 0 up');
  L.Add('    line = 6'' east, 5'' north, 7 1/2" up to 6'' east, 8'' north, 7 1/2" up');
  L.Add('    line = 6'' 10" east, 5'' north, 7 1/2" up to 6'' 10" east, 8'' north, 7 1/2" up');
  L.Add('    line = 6'' 10" east, 5'' north, 1'' 3" up to 6'' 10" east, 8'' north, 1'' 3" up');
  L.Add('    line = 7'' 8" east, 5'' north, 1'' 3" up to 7'' 8" east, 8'' north, 1'' 3" up');
  L.Add('    line = 7'' 8" east, 5'' north, 1'' 10 1/2" up to 7'' 8" east, 8'' north, 1'' 10 1/2" up');
  L.Add('    line = 8'' 6" east, 5'' north, 1'' 10 1/2" up to 8'' 6" east, 8'' north, 1'' 10 1/2" up');
  L.Add('    line = 8'' 6" east, 5'' north, 2'' 6" up to 8'' 6" east, 8'' north, 2'' 6" up');
  L.Add('    line = 9'' 4" east, 5'' north, 2'' 6" up to 9'' 4" east, 8'' north, 2'' 6" up');
  L.Add('    line = 9'' 4" east, 5'' north, 3'' 1 1/2" up to 9'' 4" east, 8'' north, 3'' 1 1/2" up');
  L.Add('    line = 10'' 2" east, 5'' north, 3'' 1 1/2" up to 10'' 2" east, 8'' north, 3'' 1 1/2" up');
  L.Add('  end');
  L.Add('end');
end;

end.
